# PyTorch Tensor 基础练习

这份 Notebook 用于练习 PyTorch 的 Tensor。请从上到下完成，每道题只修改 `TODO` 区域，然后运行该单元格。看到 `✅ 通过` 就说明结果符合要求。

遇到问题时，先观察 Tensor 的 `shape`、`dtype` 和 `device`，尽量查阅函数文档或使用 `help(torch.xxx)`。本练习暂不涉及自动求导。

In [3]:
import torch

print("PyTorch 版本:", torch.__version__)
print("CUDA 可用:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

PyTorch 版本: 2.14.0+cu130
CUDA 可用: True
GPU: NVIDIA GeForce RTX 4060 Laptop GPU


## 第一部分：创建 Tensor

### 练习 1：用不同方式创建 Tensor ⭐

请创建：

1. `a`：内容为 `[0, 2, 4, 6, 8]`、类型为 `torch.int64` 的一维 Tensor。
2. `b`：从 `-1` 到 `1` 均匀取 5 个数的 Tensor。
3. `c`：一个 $3\times3$ 的单位矩阵。

In [4]:
# TODO：请替换下面的 None
a = torch.tensor(data=[0,2,4,6,8],dtype=torch.int64)
b = torch.linspace(-1,1,5)
c = torch.eye(3,3)

# 自动检查
assert isinstance(a, torch.Tensor)
assert torch.equal(a, torch.tensor([0, 2, 4, 6, 8], dtype=torch.int64))
assert torch.allclose(b, torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0]))
assert torch.equal(c, torch.eye(3))
print("✅ 练习 1 通过")

✅ 练习 1 通过


### 练习 2：读取 Tensor 的属性 ⭐

不要直接写出数字。请通过 Tensor 的属性或方法得到 `x` 的形状、维数、元素总数和数据类型。

In [5]:
x = torch.zeros(2, 3, 4, dtype=torch.float32)

# TODO：请替换下面的 None
x_shape = x.shape    #形状
x_ndim = x.ndim      #维度
x_numel = x.numel()  #元素总数
x_dtype = x.dtype    #数据类型

assert x_shape == torch.Size([2, 3, 4])
assert x_ndim == 3
assert x_numel == 24
assert x_dtype == torch.float32
print("✅ 练习 2 通过")

✅ 练习 2 通过


## 第二部分：索引与形状变换

### 练习 3：索引和切片 ⭐⭐

对于下面的 $4\times5$ Tensor：

1. 取出第一行，保存为 `first_row`。
2. 取出最后一列，保存为 `last_column`。
3. 取出第 2～3 行、第 2～4 列组成的区域，保存为 `middle_block`。
4. 复制 `x` 得到 `changed`，把其中大于 15 的元素改成 -1，不能修改原来的 `x`。

In [6]:
x = torch.arange(1, 21).reshape(4, 5)
original_x = x.clone()

# TODO
first_row = x[0]
last_column = x[:,-1]
middle_block = x[1:3,1:4]
changed = torch.where(original_x>15,-1,original_x)  #where不会修改原张量，而是产生新张量

assert torch.equal(first_row, torch.tensor([1, 2, 3, 4, 5]))
assert torch.equal(last_column, torch.tensor([5, 10, 15, 20]))
assert torch.equal(middle_block, torch.tensor([[7, 8, 9], [12, 13, 14]]))
assert torch.equal(changed, torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [-1, -1, -1, -1, -1]]))
assert torch.equal(x, original_x), "原始 Tensor x 不应被修改"
print("✅ 练习 3 通过")

✅ 练习 3 通过


### 练习 4：reshape、flatten 和 permute ⭐⭐

给定形状为 `(2, 3, 4)` 的 `x`：

1. 将所有元素展平成一维，保存为 `flat`。
2. 将维度顺序改成 `(0, 2, 1)`，保存为 `permuted`。
3. 在不改变元素顺序的情况下，把 `x` 变成 `(6, 4)`，保存为 `matrix`。

In [7]:
x = torch.arange(24).reshape(2, 3, 4)

# TODO
flat = x.flatten()            #展平成一维
permuted = x.permute(0,2,1)   #改变维度顺序
matrix = x.reshape(6,4)       #修改形状

assert flat.shape == (24,) and torch.equal(flat, torch.arange(24))
assert permuted.shape == (2, 4, 3)
assert permuted[1, 2, 1].item() == x[1, 1, 2].item()
assert matrix.shape == (6, 4) and torch.equal(matrix.flatten(), torch.arange(24))
print("✅ 练习 4 通过")

✅ 练习 4 通过


### 练习 5：增加和删除长度为 1 的维度 ⭐⭐

一张灰度图 `image` 的形状是 `(28, 28)`。神经网络通常要求输入形状为 `(批量, 通道, 高, 宽)`。

1. 增加批量维和通道维，得到形状 `(1, 1, 28, 28)` 的 `batched_image`。
2. 删除所有长度为 1 的维度，得到形状 `(28, 28)` 的 `restored_image`。

In [8]:
image = torch.rand(28, 28)

# TODO
batched_image = image.unsqueeze(0).unsqueeze(0)      #unsqueeze增加维度
restored_image = batched_image.squeeze()             #删除长度为1的维度

assert batched_image.shape == (1, 1, 28, 28)
assert restored_image.shape == (28, 28)
assert torch.equal(restored_image, image)
print("✅ 练习 5 通过")

✅ 练习 5 通过


## 第三部分：组合与数学运算

### 练习 6：cat 与 stack ⭐⭐

组合 `a` 和 `b`，分别得到：

- `vertical`：形状 `(4, 3)`。
- `horizontal`：形状 `(2, 6)`。
- `stacked`：增加一个新维度，形状 `(2, 2, 3)`。

In [ ]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])

# TODO
vertical = torch.cat([a,b])           #cat是在不同维度上拼接，不会增加维度,dim=0代表最外面的括号的内容拼接，
print(vertical.shape)                       #dim=1表示第二外面的括号的内容拼接，以此类推
horizontal = torch.cat([a,b],1)
print(horizontal.shape)
stacked = torch.stack([a,b],2)
print(stacked.shape)
stacked = torch.stack([a,b])          #stack是在新的维度上拼接
print(stacked.shape)
#cat是在某一个维度上倍长，stack是新增加一个维度（大小为2）
assert vertical.shape == (4, 3) and vertical[-1, -1].item() == 12
assert horizontal.shape == (2, 6) and horizontal[0, 3].item() == 7
assert stacked.shape == (2, 2, 3) and torch.equal(stacked[1], b)
print("✅ 练习 6 通过")

torch.Size([4, 3])
torch.Size([2, 6])
torch.Size([2, 3, 2])
torch.Size([2, 2, 3])
✅ 练习 6 通过


### 练习 7：逐元素运算与矩阵乘法 ⭐⭐

分别计算 `a` 和 `b` 的逐元素乘积 `elementwise_product`，以及矩阵乘积 `matrix_product`。

In [ ]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])

# TODO
elementwise_product = a*b       #逐元素乘积  
matrix_product = a@b            #矩阵乘积

assert torch.equal(elementwise_product, torch.tensor([[5.0, 12.0], [21.0, 32.0]]))
assert torch.equal(matrix_product, torch.tensor([[19.0, 22.0], [43.0, 50.0]]))
print("✅ 练习 7 通过")

✅ 练习 7 通过


### 练习 8：广播机制 ⭐⭐⭐

1. 将长度为 4 的 `bias` 加到 `x` 的每一行，得到 `with_bias`。
2. 分别计算每一列的均值和标准差，并把每一列标准化，结果保存为 `normalized`。计算标准差时使用 `unbiased=False`。

In [28]:
x = torch.tensor([[1.0, 2.0, 3.0, 4.0],
                  [5.0, 6.0, 7.0, 8.0],
                  [9.0, 10.0, 11.0, 12.0]])
bias = torch.tensor([0.1, 0.2, 0.3, 0.4])

# TODO
with_bias = x+bias
print(with_bias)
column_mean = torch.mean(x,dim=0)
print(column_mean)
column_std = torch.std(x,dim=0,unbiased=False)
print(column_std)
normalized = (x - column_mean) / column_std
print(normalized)
assert torch.allclose(with_bias[0], torch.tensor([1.1, 2.2, 3.3, 4.4]))
assert column_mean.shape == (4,) and torch.allclose(column_mean, torch.tensor([5.0, 6.0, 7.0, 8.0]))
assert column_std.shape == (4,)
assert torch.allclose(normalized.mean(dim=0), torch.zeros(4), atol=1e-6)
assert torch.allclose(normalized.std(dim=0, unbiased=False), torch.ones(4), atol=1e-6)
print("✅ 练习 8 通过")

tensor([[ 1.1000,  2.2000,  3.3000,  4.4000],
        [ 5.1000,  6.2000,  7.3000,  8.4000],
        [ 9.1000, 10.2000, 11.3000, 12.4000]])
tensor([5., 6., 7., 8.])
tensor([3.2660, 3.2660, 3.2660, 3.2660])
tensor([[-1.2247, -1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247,  1.2247]])
✅ 练习 8 通过


### 练习 9：聚合运算 ⭐⭐

计算：

1. 每一行的和 `row_sums`。
2. 每一列的最大值 `column_max_values` 及其行索引 `column_max_indices`。
3. 所有元素的平均值 `global_mean`。

In [30]:
x = torch.tensor([[3.0, 7.0, 1.0],
                  [9.0, 2.0, 5.0],
                  [4.0, 8.0, 6.0]])

# TODO
row_sums = torch.sum(x,dim=1)
column_max_values = torch.max(x,dim=0).values
column_max_indices = torch.max(x,dim=0).indices
global_mean = torch.mean(x)
print(row_sums)
print(column_max_values)
print(column_max_indices)
print(global_mean)
assert torch.equal(row_sums, torch.tensor([11.0, 16.0, 18.0]))
assert torch.equal(column_max_values, torch.tensor([9.0, 8.0, 6.0]))
assert torch.equal(column_max_indices, torch.tensor([1, 2, 2]))
assert torch.isclose(global_mean, torch.tensor(5.0))
print("✅ 练习 9 通过")

tensor([11., 16., 18.])
tensor([9., 8., 6.])
tensor([1, 2, 2])
tensor(5.)
✅ 练习 9 通过


## 第四部分：筛选、类型与随机数

### 练习 10：布尔索引 ⭐⭐

1. 取出 `x` 中所有偶数，保存为 `even_numbers`。
2. 复制 `x` 得到 `non_negative`，将所有负数替换为 0，不能修改原来的 `x`。

In [ ]:
x = torch.tensor([-4, -3, -2, -1, 0, 1, 2, 3, 4])
original_x = x.clone()

# TODO
even_numbers = x[x%2==0]
non_negative = torch.where(x<0,0,x)
print(even_numbers)
print(non_negative)

assert torch.equal(even_numbers, torch.tensor([-4, -2, 0, 2, 4]))
assert torch.equal(non_negative, torch.tensor([0, 0, 0, 0, 0, 1, 2, 3, 4]))
assert torch.equal(x, original_x)
print("✅ 练习 10 通过")

tensor([-4, -2,  0,  2,  4])
tensor([0, 0, 0, 0, 0, 1, 2, 3, 4])
✅ 练习 10 通过


### 练习 11：数据类型转换 ⭐⭐

将整数 Tensor `scores` 转换为 `torch.float32`，保存为 `float_scores`，再计算它的平均值 `average`。

In [35]:
scores = torch.tensor([80, 90, 75, 95])

# TODO
float_scores = scores.float()
average = torch.mean(float_scores)

assert float_scores.dtype == torch.float32
assert torch.isclose(average, torch.tensor(85.0))
print("✅ 练习 11 通过")

✅ 练习 11 通过


### 练习 12：可复现的随机数 ⭐⭐

使用随机种子 `42` 生成一个形状为 `(2, 3)` 的标准正态分布 Tensor `random_a`。重新设置同一个种子，再生成 `random_b`，使二者完全相同。

In [42]:
# TODO
torch.manual_seed(42)
random_a = torch.randn(2,3)
torch.manual_seed(42)
random_b = torch.randn(2,3)
print(random_a,'\n',random_b)

assert random_a.shape == (2, 3)
assert torch.equal(random_a, random_b)
assert torch.allclose(random_a, torch.tensor([[0.3367, 0.1288, 0.2345], [0.2303, -1.1229, -0.1863]]), atol=1e-4)
print("✅ 练习 12 通过")

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]]) 
 tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
✅ 练习 12 通过


## 第五部分：设备与综合练习

### 练习 13：CPU 与 CUDA 设备 ⭐⭐

1. CUDA 可用时选择 `cuda`，否则选择 `cpu`，保存为 `device`。
2. 把 `x` 移动到该设备，保存为 `x_on_device`。
3. 在该设备上计算 $x^2+1$，保存为 `result`。
4. 将结果移回 CPU，保存为 `result_cpu`。

In [44]:
x = torch.tensor([1.0, 2.0, 3.0])

# TODO
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x_on_device = x.to(device)
result = x_on_device**2+1
result_cpu = result.cpu()
print(device)
print(x_on_device)
print(result)
print(result_cpu)

expected_device_type = "cuda" if torch.cuda.is_available() else "cpu"
assert isinstance(device, torch.device)
assert device.type == expected_device_type
assert x_on_device.device.type == expected_device_type
assert result.device.type == expected_device_type
assert result_cpu.device.type == "cpu"
assert torch.equal(result_cpu, torch.tensor([2.0, 5.0, 10.0]))
print(f"✅ 练习 13 通过，计算设备：{device}")

cuda
tensor([1., 2., 3.], device='cuda:0')
tensor([ 2.,  5., 10.], device='cuda:0')
tensor([ 2.,  5., 10.])
✅ 练习 13 通过，计算设备：cuda


### 练习 14：clone 与共享数据 ⭐⭐⭐

创建 `x` 的真正副本 `independent_copy`。将副本的第一个元素改为 `100`，同时保证原来的 `x` 不发生变化。

In [45]:
x = torch.tensor([1, 2, 3])

# TODO
independent_copy = x.clone()
# 在下一行修改 independent_copy 的第一个元素
independent_copy[0] = 100
assert torch.equal(x, torch.tensor([1, 2, 3]))
assert torch.equal(independent_copy, torch.tensor([100, 2, 3]))
assert x.data_ptr() != independent_copy.data_ptr(), "两个 Tensor 不应共享同一块数据"
print("✅ 练习 14 通过")

✅ 练习 14 通过


### 练习 15：综合挑战——批量样本标准化与相似度 ⭐⭐⭐

`samples` 表示 3 个样本，每个样本包含 4 个特征。请完成：

1. 分别计算每个样本的特征均值 `sample_means`，保持结果形状为 `(3, 1)`。
2. 分别计算每个样本的特征标准差 `sample_stds`，使用 `unbiased=False` 并保持形状为 `(3, 1)`。
3. 利用广播完成逐样本标准化，得到 `normalized_samples`。
4. 计算标准化样本两两之间的点积，得到形状为 `(3, 3)` 的 `similarity_matrix`。

限制：不能使用 Python 的 `for` 循环。

In [ ]:
samples = torch.tensor([[1.0, 2.0, 3.0, 4.0],
                        [2.0, 4.0, 6.0, 8.0],
                        [4.0, 3.0, 2.0, 1.0]])

# TODO
sample_means = torch.mean(samples,dim=1,keepdim=True)                       #keepdim为保持原矩阵维度
sample_stds = torch.std(samples,dim=1,unbiased=False,keepdim=True)
normalized_samples = (samples-sample_means)/sample_stds
similarity_matrix = normalized_samples@normalized_samples.T
print(sample_means)
print(sample_stds)
print(normalized_samples)
print(similarity_matrix)
assert sample_means.shape == (3, 1)
assert sample_stds.shape == (3, 1)
assert normalized_samples.shape == samples.shape
assert torch.allclose(normalized_samples.mean(dim=1), torch.zeros(3), atol=1e-6)
assert torch.allclose(normalized_samples.std(dim=1, unbiased=False), torch.ones(3), atol=1e-6)
assert similarity_matrix.shape == (3, 3)
assert torch.allclose(similarity_matrix, similarity_matrix.T, atol=1e-6)
assert torch.allclose(similarity_matrix.diag(), torch.full((3,), 4.0), atol=1e-5)
print("✅ 练习 15 通过，你已经完成 Tensor 基础综合挑战！")

tensor([[2.5000],
        [5.0000],
        [2.5000]])
tensor([[1.1180],
        [2.2361],
        [1.1180]])
tensor([[-1.3416, -0.4472,  0.4472,  1.3416],
        [-1.3416, -0.4472,  0.4472,  1.3416],
        [ 1.3416,  0.4472, -0.4472, -1.3416]])
tensor([[ 4.0000,  4.0000, -4.0000],
        [ 4.0000,  4.0000, -4.0000],
        [-4.0000, -4.0000,  4.0000]])
✅ 练习 15 通过，你已经完成 Tensor 基础综合挑战！


## 完成后的自我检查

完成全部练习后，请确认自己能够解释：

- `reshape`、`flatten`、`squeeze`、`unsqueeze` 和 `permute` 分别改变了什么。
- `cat` 与 `stack` 的主要区别。
- `*` 与 `@` 对矩阵执行的运算为何不同。
- 广播为什么允许 `(3, 4)` 和 `(4,)` 相加。
- 为什么复制 Tensor 时有时需要 `clone()`。
- 如何让同一段代码自动选择 CUDA 或 CPU。

把你完成后的 Notebook 交给我，我可以逐题检查，并针对容易混淆的知识点继续讲解。